"""
Myth Museum - Streamlit Video Generator

Interactive web interface for generating myth-busting YouTube Shorts.

Run with:
    streamlit run streamlit_app.py
"""

import asyncio
import sys
from pathlib import Path

# Ensure pipeline modules are importable
sys.path.insert(0, str(Path(__file__).parent))

import streamlit as st

# Page configuration
st.set_page_config(
    page_title="Myth Museum Video Generator",
    page_icon="🏛️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS for better styling
st.markdown("""
<style>
    .main-header {
        font-size: 2.5rem;
        font-weight: bold;
        color: #1E3A5F;
        text-align: center;
        margin-bottom: 1rem;
    }
    .sub-header {
        font-size: 1.2rem;
        color: #6B7280;
        text-align: center;
        margin-bottom: 2rem;
    }
    .stProgress > div > div > div > div {
        background-color: #1E3A5F;
    }
    .status-box {
        padding: 1rem;
        border-radius: 0.5rem;
        background-color: #F3F4F6;
        margin: 1rem 0;
    }
    .success-box {
        background-color: #D1FAE5;
        border: 1px solid #10B981;
    }
    .error-box {
        background-color: #FEE2E2;
        border: 1px solid #EF4444;
    }
</style>
""", unsafe_allow_html=True)


# ============================================================================
# Helper Functions
# ============================================================================

def get_style_options():
    """Get available visual styles."""
    return {
        "oil_painting_cartoon": "Oil Painting Cartoon - Renaissance style, warm and scholarly",
        "watercolor_fantasy": "Watercolor Fantasy - Dreamy, mythological storybook aesthetic",
        "cinematic": "Cinematic - Hollywood movie quality, dramatic lighting",
        "realistic": "Realistic - Photorealistic documentary style",
        "vintage_sepia": "Vintage Sepia - Aged photography, historical feel",
        "sci_fi_cinematic": "Sci-Fi Cinematic - Interstellar/Star Trek aesthetic",
        "pixar_3d": "Pixar 3D - Animated 3D cartoon style",
        "watercolor": "Watercolor - Soft, dreamy artistic style",
    }


def get_arc_options():
    """Get available narrative arcs."""
    return {
        "myth_buster": "Myth Buster - Debunking common beliefs (6 scenes: Mystery → Evidence → Revelation)",
        "historical_figure": "Historical Figure - Biographical content (6 scenes: Portrait → Legacy)",
        "lost_civilization": "Lost Civilization - Ancient history mysteries (6 scenes: Ruins → Discovery)",
    }


def generate_script_suggestion(topic: str) -> str:
    """Generate a script suggestion for the given topic."""
    # Default template - in production this would use LLM
    return f"""Think you know the truth about {topic}?

That's the story we've all been told. But here's what the evidence actually shows.

[Main content about {topic} goes here - this would be generated by LLM based on research]

The reality is far more interesting than the myth. Most people get this completely wrong.

So the next time someone mentions {topic}, you'll know the real story. The truth is often stranger than fiction.
"""


def detect_best_style(topic: str) -> str:
    """Detect the best visual style based on topic."""
    topic_lower = topic.lower()
    
    if any(word in topic_lower for word in ["greek", "odyssey", "zeus", "myth", "god"]):
        return "watercolor_fantasy"
    elif any(word in topic_lower for word in ["space", "galaxy", "star", "planet", "cosmos"]):
        return "sci_fi_cinematic"
    elif any(word in topic_lower for word in ["edison", "tesla", "industrial", "inventor"]):
        return "vintage_sepia"
    elif any(word in topic_lower for word in ["egypt", "pyramid", "sphinx", "ancient"]):
        return "cinematic"
    else:
        return "oil_painting_cartoon"


def detect_best_arc(topic: str) -> str:
    """Detect the best narrative arc based on topic."""
    topic_lower = topic.lower()
    
    if any(word in topic_lower for word in ["da vinci", "einstein", "edison", "napoleon", "beethoven"]):
        return "historical_figure"
    elif any(word in topic_lower for word in ["egypt", "maya", "aztec", "atlantis", "civilization"]):
        return "lost_civilization"
    else:
        return "myth_buster"


async def run_video_generation(
    topic: str,
    script: str,
    style: str,
    arc: str,
    progress_callback,
    status_callback,
) -> Path:
    """
    Run the video generation pipeline.
    
    Args:
        topic: Video topic
        script: Voiceover script
        style: Visual style ID
        arc: Narrative arc ID
        progress_callback: Function to update progress bar
        status_callback: Function to update status text
        
    Returns:
        Path to generated video
    """
    from pipeline.generate_short import (
        ShortVideoGenerator,
        GenerationConfig,
        PreFlightCheck,
    )
    from pipeline.tts import get_audio_duration
    
    # Phase 0: Pre-flight checks
    status_callback("Phase 0: Running pre-flight checks...")
    progress_callback(0.05)
    
    preflight = PreFlightCheck()
    if not preflight.run_all_checks(verbose=False):
        errors = "\n".join(preflight.checks_failed)
        raise RuntimeError(f"Pre-flight checks failed:\n{errors}")
    
    progress_callback(0.10)
    
    # Create generator
    generator = ShortVideoGenerator()
    
    # Create config
    config = GenerationConfig(
        topic=topic,
        script=script,
        image_quality="high",
        subtitle_style="punch",
        auto_prompts=True,
    )
    
    # Phase 1: Setup
    status_callback("Phase 1: Setting up output folder...")
    progress_callback(0.15)
    
    # Phase 2: Script optimization
    status_callback("Phase 2: Optimizing script...")
    progress_callback(0.20)
    
    # Phase 3: Image generation
    status_callback("Phase 3: Generating images (this may take a few minutes)...")
    progress_callback(0.25)
    
    # Run the actual generation
    result = await generator.generate(config)
    
    if not result.success:
        raise RuntimeError(f"Video generation failed: {result.error}")
    
    progress_callback(1.0)
    status_callback("Complete!")
    
    return result.final_video


# ============================================================================
# Streamlit App
# ============================================================================

def main():
    # Header
    st.markdown('<div class="main-header">🏛️ Myth Museum Video Generator</div>', unsafe_allow_html=True)
    st.markdown('<div class="sub-header">Create myth-busting YouTube Shorts in minutes</div>', unsafe_allow_html=True)
    
    # Sidebar with settings
    with st.sidebar:
        st.header("⚙️ Settings")
        
        image_quality = st.selectbox(
            "Image Quality",
            options=["high", "standard", "fallback"],
            index=0,
            help="high = Imagen 3, standard = Imagen @006, fallback = stock photos"
        )
        
        subtitle_style = st.selectbox(
            "Subtitle Style",
            options=["punch", "normal"],
            index=0,
            help="punch = animated first word + keyword highlighting"
        )
        
        st.divider()
        
        st.header("📊 Pre-flight Status")
        if st.button("Run Pre-flight Checks"):
            with st.spinner("Checking dependencies..."):
                from pipeline.generate_short import PreFlightCheck
                preflight = PreFlightCheck()
                preflight.run_all_checks(verbose=False)
                
                for check in preflight.checks_passed:
                    st.success(f"✓ {check}")
                for warning in preflight.checks_warned:
                    st.warning(f"⚠ {warning}")
                for error in preflight.checks_failed:
                    st.error(f"✗ {error}")
    
    # Main content area
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Topic input
        st.header("1️⃣ Enter Topic")
        topic = st.text_input(
            "What myth do you want to bust?",
            placeholder="e.g., 'Odyssey 10 year myth', 'Napoleon was short', 'Edison invented the lightbulb'",
            key="topic_input"
        )
        
        # Generate suggestions button
        if st.button("🎯 Generate Suggestions", type="primary", disabled=not topic):
            with st.spinner("Generating suggestions..."):
                # Generate script
                suggested_script = generate_script_suggestion(topic)
                st.session_state['suggested_script'] = suggested_script
                st.session_state['suggested_style'] = detect_best_style(topic)
                st.session_state['suggested_arc'] = detect_best_arc(topic)
                st.session_state['topic'] = topic
        
        # Show suggestions if available
        if 'suggested_script' in st.session_state:
            st.divider()
            
            # Script editor
            st.header("2️⃣ Story Structure")
            script = st.text_area(
                "Edit the script (voiceover text)",
                value=st.session_state.get('suggested_script', ''),
                height=250,
                key="script_editor"
            )
            
            # Style and Arc selection
            st.header("3️⃣ Visual Style & Narrative Arc")
            
            col_style, col_arc = st.columns(2)
            
            with col_style:
                style_options = get_style_options()
                default_style = st.session_state.get('suggested_style', 'oil_painting_cartoon')
                default_index = list(style_options.keys()).index(default_style) if default_style in style_options else 0
                
                selected_style = st.radio(
                    "Visual Style",
                    options=list(style_options.keys()),
                    index=default_index,
                    format_func=lambda x: style_options[x].split(" - ")[0],
                    key="style_selection"
                )
                st.caption(style_options[selected_style].split(" - ")[1] if " - " in style_options[selected_style] else "")
            
            with col_arc:
                arc_options = get_arc_options()
                default_arc = st.session_state.get('suggested_arc', 'myth_buster')
                default_arc_index = list(arc_options.keys()).index(default_arc) if default_arc in arc_options else 0
                
                selected_arc = st.radio(
                    "Narrative Arc",
                    options=list(arc_options.keys()),
                    index=default_arc_index,
                    format_func=lambda x: arc_options[x].split(" - ")[0],
                    key="arc_selection"
                )
                st.caption(arc_options[selected_arc].split(" - ")[1] if " - " in arc_options[selected_arc] else "")
            
            st.divider()
            
            # Generate button
            st.header("4️⃣ Generate Video")
            
            if st.button("🎬 Generate Video", type="primary", use_container_width=True):
                # Progress tracking
                progress_bar = st.progress(0)
                status_text = st.empty()
                
                def update_progress(value):
                    progress_bar.progress(value)
                
                def update_status(text):
                    status_text.text(text)
                
                try:
                    with st.spinner("Generating video... This may take 5-10 minutes."):
                        # Run async generation
                        video_path = asyncio.run(run_video_generation(
                            topic=st.session_state.get('topic', topic),
                            script=script,
                            style=selected_style,
                            arc=selected_arc,
                            progress_callback=update_progress,
                            status_callback=update_status,
                        ))
                        
                        st.session_state['video_path'] = video_path
                        st.success("✅ Video generated successfully!")
                        
                except Exception as e:
                    st.error(f"❌ Generation failed: {str(e)}")
                    st.exception(e)
    
    with col2:
        # Video preview area
        st.header("📺 Preview")
        
        if 'video_path' in st.session_state and st.session_state['video_path']:
            video_path = Path(st.session_state['video_path'])
            
            if video_path.exists():
                # Video player
                st.video(str(video_path))
                
                # Download button
                with open(video_path, "rb") as f:
                    video_bytes = f.read()
                    st.download_button(
                        label="⬇️ Download Video",
                        data=video_bytes,
                        file_name=f"myth_museum_{st.session_state.get('topic', 'video')[:20]}.mp4",
                        mime="video/mp4",
                        use_container_width=True,
                    )
                
                # Show output folder
                st.info(f"📁 Output folder:\n`{video_path.parent}`")
            else:
                st.warning("Video file not found.")
        else:
            st.info("Generated video will appear here after processing.")
            
            # Show sample placeholder
            st.markdown("""
            **Workflow:**
            1. Enter a myth topic
            2. Click "Generate Suggestions"
            3. Edit script and select style
            4. Click "Generate Video"
            5. Preview and download!
            """)
    
    # Footer
    st.divider()
    st.markdown("""
    <div style="text-align: center; color: #6B7280; font-size: 0.9rem;">
        🏛️ Myth Museum • Powered by Imagen 3, Google TTS, and FFmpeg<br>
        <a href="https://github.com/AlexBBno1/MetaGPT_Myth-Museum" target="_blank">GitHub Repository</a>
    </div>
    """, unsafe_allow_html=True)


if __name__ == "__main__":
    main()
